<?php
require_once("src/exceptions/DataTypeException.php");
require_once("src/Comparable.php");
require_once("src/Object.php");
require_once("src/Boolean.php");
require_once("src/Double.php");
require_once("src/Integer.php");
require_once("src/String.php");
require_once("src/Collection.php");
require_once("src/calendar/Date.php");
require_once("src/calendar/Time.php");
require_once("src/calendar/TimeStamp.php");
require_once("src/collections/Lists.php");
require_once("src/collections/Maps.php");
require_once("src/collections/Sets.php");
require_once("src/collections/sorters/CollectionSorter.php");
require_once("src/collections/sorters/CollectionValuesSorter.php");
